{
    "Target": {
        "EntitySet": "RISK",
        "Service": "/RisksMobile/Services/RISKService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/RisksMobile/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/RisksMobile/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}